id: AA8459108
title: Toh_101-Upholding_the_Roots_of_Virtue-v2
type: translation
pechas:
- I2DFCCE0C
- I72D835F3
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-048-001
  eft-text-version: 1.2.3 2020
  title: Toh_101-Upholding_the_Roots_of_Virtue-v2
alignment_to_base:
  I2DFCCE0C/8FF8: FD10
  I72D835F3/9FC5: FD10
